name: CI Workflow

on:
  push:
    branches:
      - main # Se ejecuta en push a la rama main
  pull_request:
    branches:
      - main # Se ejecuta en los pull requests dirigidos a main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Configurar el repositorio
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Configurar la versión de Node.js (puedes ajustarla según el proyecto)
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # Cambia según la versión que necesites

    # 3. Instalar las dependencias del proyecto
    - name: Install dependencies
      run: npm install

    # 4. Ejecutar pruebas (si tu proyecto tiene pruebas configuradas)
    - name: Run tests
      run: npm test

    # 5. Realizar compilación (si tu proyecto tiene un script de build)
    - name: Build project
      run: npm run build
