name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar el repositorio
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Verificar el contenido (opcional)
      - name: List files
        run: ls -la


#comentario comentario cambio jaja
#cambio 2